### ISSUE TITLE
Adicionar URL's de API de PROD - v1, v2, v3, v4

### ISSUE THREAD

**Issue by WadsonGarbes** [WadsonGarbes/urls-pontotel#1]

**Comment by Luna-lancellotti** [comment]
https://prod.pontotel.com.br/canary/back

**Comment by WadsonGarbes** [comment]
# Aloque
alpha --> https://tinyurl.com/29uv5kz2
alpha-magenta --> https://hml.pontotel.com.br/aloque-alpha-magenta/frontend/index.html#/auth
API alpha --> https://tinyurl.com/x7uktbwk
API v1 alpha --> https://hml.pontotel.com.br/aloque-alpha/backend/api/v1/docs#
homolog --> https://tinyurl.com/4c3339sy
API homolog --> https://tinyurl.com/439fa52v
API v1 homolog --> https://hml.pontotel.com.br/aloque/backend/api/v1/docs#
prod --> https://aloque.pontotel.com.br/
API prod --> https://tinyurl.com/2s3n9exs
API v1 prod --> https://prod.pontotel.com.br/aloque/backend/api/v1/docs#/

**Comment by WadsonGarbes** [comment]
Urls adicionadas!
